### ISSUE TITLE
SyntaxError in line 80

### ISSUE THREAD

**Issue by pizzamaker** [SwartzCr/nekoatsume#10]
I'm getting an error upon trying to open the game:

$ python display.py
  File "display.py", line 80
    print sys.exc_info()[0]
            ^
SyntaxError: invalid syntax

**Comment by SwartzCr** [comment]
I can't seem to reproduce this, maybe try wiping your repo and downloading it again?
unless one of @brianshumate's pep fixes broke some syntax?

**Comment by SwartzCr** [comment]
or maybe commit your changes to a personal fork - then I can check it out and hopefully reproduce the error

**Comment by pizzamaker** [comment]
Just tried wiping and downloading again. Same error. Weird.

**Comment by brianshumate** [comment]
This is likely a Python 2 vs. Python 3 issue; I reproduced it in Python 3.

So we can fix the print statements and figure out what to do about raw_input and make it 2 and 3 compatible. I can work on this later this evening.

**Comment by pizzamaker** [comment]
Please accept the pull request :)

**Comment by SwartzCr** [comment]
done, sorry didn't see the PR initially

**Comment by pizzamaker** [comment]
Now it works! Thanks you two.
