### ISSUE TITLE
Add color coding

### ISSUE THREAD

**Issue by pizzamaker** [SwartzCr/nekoatsume#12]
It would be better for reading if strings had different colors. Is it feasible?

**Comment by SwartzCr** [comment]
I actually started trying to do this
it'll require a lot of formating  and encoding/decoding things.
If someone can point me to examples of it it'll go faster, otherwise I can take a crack at it in a few weeks (or maybe @brianshumate want's to play with it?)
But yes, I also want this feature

**Comment by brianshumate** [comment]
Here's what it looks like:

<img width="1065" alt="screenshot" src="https://cloud.githubusercontent.com/assets/77563/12278346/9fb6fc4a-b94e-11e5-9465-e691fc057b5a.png">

**Comment by pizzamaker** [comment]
Nice, @brianshumate! I suggest having the items in a different color relative to the beginning of the sentence.

**Comment by brianshumate** [comment]
<img width="1065" alt="updated_screen" src="https://cloud.githubusercontent.com/assets/77563/12282768/b6a45022-b96e-11e5-9fc2-8896ec1b5428.png">

**Comment by phillipjphry** [comment]
Personally I like the whole line to have colour. Different colours for (toy) and (food), then a standard colour for a description. Something easy to read. I'd love to work on this, would that be okay? I have no idea what the etiquette is here. Do I just clone and run with it? New branch? Seriously, how do I get in on this.

**Comment by brianshumate** [comment]
Hey @phillipjphry thanks for the interest! :smile_cat: 

I think we might be good on the colorization for now; there was some discussion in here and offline about how best to handle this and I think so far, the idea of having the place labels consistently colored was preferred to having a solid line of color that also includes the actual message text. 

That said, there are some exceptions where the game is trying to indicate a "warning" or "failure" message and in those cases, the actual message text is yellow or red accordingly.

I have a new PR over in #23 that gets colors pretty well as we want them, but there definitely could be room for improvement.

With respect to contributions, I think we're just doing things sort of informally right now with a fork/branch/PR style so far. We have some other open issues that need help, and I think suggestions are always welcome, too so feel free to dive in however you'd like.

**Comment by phillipjphry** [comment]
Thanks! I'll noodle around till I find one I think I can tackle.

**Comment by SwartzCr** [comment]
I'd love to see the money light up, or even certain cat names
this might be able to be done by storing their names with color codes as part of them

**Comment by brianshumate** [comment]
That's a good idea.

So far in quick play, I have not seen any cats or collected any money. I guess I need to leave the game open longer. :smile_cat:

**Comment by phillipjphry** [comment]
I made a droplet and am going to be checking in on it every once in a while, let's see where it goes!

**Comment by brianshumate** [comment]
:wave: We can probably close this one for now as remaining ideas for work are captured over in #52.

**Comment by SwartzCr** [comment]
Okay! @phillipjphry hows your game going?

**Comment by phillipjphry** [comment]
@swartzcr good! I got caught up in making a cyberpunk mud after noodling
with this.

Now, just work. :P
