### ISSUE TITLE
Modularize and have top-level executable

### ISSUE THREAD

**Issue by brianshumate** [SwartzCr/nekoatsume#19]
I think the project structure and user experience could be benefitted by having a modular structure with code and resources stored in a typical file system hierarchy.

So we'd have a structure like this:

```
├── LICENSE.txt
├── README.md
├── lib                                                 # game code as a module
│   ├── __init__.py
│   ├── buy_menu.py
│   ├── data_constructor.py
│   ├── display.py
│   ├── placement.py
│   ├── printer.py
│   └── update.py
├── nekoatsume.py                                       # user executable
├── share                                               # shared resources
│   └── screenshot.png
└── var                                                 # game data
    └── data.json
```

Then, instead of doing `python display.py`, users can do `./nekoatsume.py` to start the game.

This will keep things a little more organized as well IMO.

What do you think?

I have [a branch](https://github.com/brianshumate/nekoatsume/tree/nekoatsume-cmd) on my fork already that is working well in this way. :smile:

**Comment by SwartzCr** [comment]
I really like this idea. I'll test out your branch and see if I have comments

**Comment by SwartzCr** [comment]
looks great ~except~ that you forgot to include the var directory, so currently it errors out on trying to write the item list

**Comment by brianshumate** [comment]
:+1: I think that's because git doesn't like to add empty dirs and `data.json` is in the `.gitignore`. I added a `README.md` in `data` and committed that so that the directory is present.
