### ISSUE TITLE
Available options doubled

### ISSUE THREAD

**Issue by brianshumate** [SwartzCr/nekoatsume#24]
When player inputs an unknown option, there are basically two listings of the available options because the while loop in for example, the `menu()` function of _placement_ constantly calls `printer.prompt` even after a call to `printer.invalid`, so you get output like this:

![screen shot 2016-02-03 at 5 15 37 pm](https://cloud.githubusercontent.com/assets/77563/12798923/0b6f21ae-ca9a-11e5-83d1-5603faa74cb6.png)

where _Your options are_ is shown twice.

**Comment by SwartzCr** [comment]
can merge @tennysonholloway 's change as soon as he fixes merge conflicts, thanks tennyson!
