### ISSUE TITLE
game data gets overwritten every time you start up the game

### ISSUE THREAD

**Issue by SwartzCr** [SwartzCr/nekoatsume#36]
oh no!

**Comment by rolandshoemaker** [comment]
Are you sure? It seems like my state sticks around (from master start game -> buy item -> place item in yard -> quit -> restart -> examine yard shows the placed item).

**Comment by SwartzCr** [comment]
fixed this - it was a bug in tick, so it only happened when food was present.
The problem was that I was getting len(toy['occupied']) when it should be len(toy['occupant'])
