### ISSUE TITLE
Add a free license

### ISSUE THREAD

**Issue by pizzamaker** [SwartzCr/nekoatsume#6]
I suggest AGPLv3+ :)

**Comment by SwartzCr** [comment]
@brianshumate, as the only other contributor to this repo, how would you feel about this license addition?

**Comment by brianshumate** [comment]
I am good with any reasonable license addition, but it should be your call. :)

**Comment by SwartzCr** [comment]
fixed in https://github.com/SwartzCr/nekoatsume/commit/6ca0adbbdc45159eee191d540768a14a0f896593 :D
